# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x07\n\x05\x45mpty\"2\n\rListenRequest\x12\x15\n\x02me\x18\x02 \x01(\x0b\x32\t.UserInfoJ\x04\x08\x01\x10\x02J\x04\x08\x03\x10\x04\")\n\x14\x43onnectServerReqeust\x12\x11\n\tuser_name\x18\x01 \x01(\t\"m\n\x15\x43onnectServerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x04user\x18\x02 \x01(\x0b\x32\t.UserInfoH\x00\x12\x17\n\rerror_message\x18\x03 \x01(\tH\x00\x42\x0f\n\ruser_or_error\"O\n\x08UserInfo\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x19\n\x0crandom_color\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_random_colorJ\x04\x08\x02\x10\x03\"b\n\x0b\x43hatRequest\x12\x19\n\x06sender\x18\x01 \x01(\x0b\x32\t.UserInfo\x12\x11\n\x07message\x18\x02 \x01(\tH\x00\x42\r\n\x0bmsg_or_fileJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07\"j\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12 \n\x08\x63hat_req\x18\x02 \x01(\x0b\x32\x0c.ChatRequestH\x00\x12\x17\n\rerror_message\x18\x03 \x01(\tH\x00\x42\x0e\n\x0creq_or_error2\x9b\x01\n\x08\x43hatting\x12>\n\rConnectServer\x12\x15.ConnectServerReqeust\x1a\x16.ConnectServerResponse\x12-\n\nListenChat\x12\x0e.ListenRequest\x1a\r.ChatResponse0\x01\x12 \n\x08SendChat\x12\x0c.ChatRequest\x1a\x06.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=14
  _EMPTY._serialized_end=21
  _LISTENREQUEST._serialized_start=23
  _LISTENREQUEST._serialized_end=73
  _CONNECTSERVERREQEUST._serialized_start=75
  _CONNECTSERVERREQEUST._serialized_end=116
  _CONNECTSERVERRESPONSE._serialized_start=118
  _CONNECTSERVERRESPONSE._serialized_end=227
  _USERINFO._serialized_start=229
  _USERINFO._serialized_end=308
  _CHATREQUEST._serialized_start=310
  _CHATREQUEST._serialized_end=408
  _CHATRESPONSE._serialized_start=410
  _CHATRESPONSE._serialized_end=516
  _CHATTING._serialized_start=519
  _CHATTING._serialized_end=674
# @@protoc_insertion_point(module_scope)
